version: '3.7'
# Removed subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1
# I had this:
# cat ~/.docker/config.json
# {"auths":{},"credsStore":"", "credsStore":"desktop","stackOrchestrator":"swarm"}
# I updated to this:
# {"auths":{},"credsStore":"","stackOrchestrator":"swarm"}
services:
  naming-server:
    image: enriquemarquez/naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - todo-web-application-network
      
  entity-administracion:
    image: enriquemarquez/entity-administracion:0.0.1-SNAPSHOT
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: # Start the depends_on first
      - mysql
      - naming-server
      - entity-publicaciones
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: todos
      RDS_USERNAME: todos-user
      RDS_PASSWORD: dummytodos
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - todo-web-application-network

  entity-publicaciones:
    image: enriquemarquez/entity-publicaciones:0.0.1-SNAPSHOT
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    depends_on: # Start the depends_on first
      - mysql
      - naming-server
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: todos
      RDS_USERNAME: todos-user
      RDS_PASSWORD: dummytodos
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - todo-web-application-network
      
  microservice-administracion:
    image: enriquemarquez/microservice-administracion:0.0.1-SNAPSHOT
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    depends_on: # Start the depends_on first      
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka      
    networks:
      - todo-web-application-network 

  microservice-publicaciones:
    image: enriquemarquez/microservice-publicaciones:0.0.1-SNAPSHOT
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "8083:8083"
    restart: always
    depends_on: # Start the depends_on first      
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - todo-web-application-network
      
  microservice-solicitudes:
    image: enriquemarquez/microservice-solicitudes:0.0.1-SNAPSHOT
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - "8084:8084"
    restart: always
    depends_on: # Start the depends_on first      
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
    networks:
      - todo-web-application-network 
            
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root       
      MYSQL_USER: todos-user
      MYSQL_PASSWORD: dummytodos
      MYSQL_DATABASE: todos
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - todo-web-application-network
  
# Volumes
volumes:
  mysql-database-data-volume:

networks:
  todo-web-application-network: